# Autogenerated wrapper script for msquic_jll for aarch64-apple-darwin
export libmsquic

JLLWrappers.@generate_wrapper_header("msquic")
JLLWrappers.@declare_library_product(libmsquic, "@rpath/libmsquic.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmsquic,
        "lib/libmsquic.2.5.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
