# Autogenerated wrapper script for msquic_jll for i686-linux-musl
export libmsquic

JLLWrappers.@generate_wrapper_header("msquic")
JLLWrappers.@declare_library_product(libmsquic, "libmsquic.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmsquic,
        "lib/libmsquic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
